import 'dotenv/config';
import './events/resourceStart';
import './prototype/player';
import './systems/account';
import './systems/charCreator';
import './systems/keyManager';
import './systems/login';
import './systems/tick';
import './systems/world';
