announce = false
debug = true
description = 'test'
gamemode = 'Freeroam'
host = '127.0.0.1'
language = 'de'
modules = [ 'js-module' ]
name = 'TestServer'
players = 2
port = 7788
resources = [ 'livingyou' ]
website = 'beyonddark.de'
token = '4b05d683-5e21-4861-a14a-fdd54cc70bab'