# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: LivingYou

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  checkout:
    name: Checkout Repository
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3.0.2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

  get-data:
    name: Get needed data
    runs-on: self-hosted
    needs: checkout

    outputs:
      current_branch: ${{ steps.branch-name.outputs.current_branch }}
      version: ${{ steps.version.outputs.version }}
      description: ${{ steps.version.outputs.description }}

    steps:
    - name: Get Branch name
      id: branch-name
      uses: tj-actions/branch-names@v5.2
    - name: Generate Version
      id: version
      uses: codacy/git-version@2.5.4

  setup-node:
    name: Setup Node.js
    runs-on: self-hosted

    steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v2.2.1
      with:
        version: 7.1.5
    - name: Use Node.js 17.7.0
      uses: actions/setup-node@v3.2.0
      with:
        node-version: 17.7.0
        cache: 'pnpm'

  pre-build:
    name: Prepare Build Environment
    runs-on: self-hosted
    needs: [checkout, setup-node]

    steps:
    - name: Disable Dev Mode
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: build-options.js
        contents: |
          export default {
            devMode: false,
          };
        write-mode: overwrite
    - name: Install pnpm packages
      run: pnpm install
    - name: Download alt:V Server
      run: pnpm run update --if-present

  build:
    name: Build Script
    runs-on: self-hosted
    needs: pre-build

    steps:
    - name: Build Script
      run: pnpm run start --if-present

  test:
    name: Test Script
    runs-on: self-hosted
    needs: build

    steps:
    - name: Grant alt:V Permissions to run
      run: chmod 777 altv-server && chmod 777 start.sh
    #- name: Run alt:V Server
    #  run: ./start.sh

  release:
    name: Publish Release
    runs-on: self-hosted
    needs: [get-data, test]

    steps:
    - name: Publish new release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        prerelease: ${{ needs.get-data.outputs.current_branch == 'dev' }}
        tag_name: ${{ needs.get-data.outputs.version }}
        release_name: Release ${{ needs.get-data.outputs.version }}
        body: ${{ needs.get-data.outputs.description }}
