# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: LivingYou

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  version:
    runs-on: self-hosted
    
    outputs:
      version: ${{ steps.version.outputs.version }}
      
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - name: Git Version
        id: version
        uses: codacy/git-version@2.5.4
      
  build:
    runs-on: self-hosted
    needs: version

    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
      with:
        version: 7.1.5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - uses: DamianReeves/write-file-action@v1.0
      with:
        path: build-options.js
        contents: |
          export default {
            devMode: false,
          };
        write-mode: overwrite
    - run: pnpm install
    - run: pnpm run update --if-present
    - run: pnpm run start --if-present
    - run: chmod 777 altv-server && chmod 777 start.sh
    - run: ./start.sh
    #- run: echo ${{ needs.version.outputs.version }}
    #- uses: actions/create-release@v1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    #    tag_name: ${{ env.VERSION }}
    #    release_name: ${{ env.VERSION }}
